### ISSUE TITLE
ОДНО ИЗ САМЫХ ПОЧИТАЕМЫХ, ПОЧТИ НАРАВНЕ С ПОКРОВИТЕЛЕМ КОНЕВОДСТВА, КОТОРОГО ЗОВУТ ДЖЕСЕГЕЙ (КОНИ У ЯКУТОВ ВЕСЬМА САКРАЛЬНЫЕ ЖИВОТНЫЕ, ПОЧТИ КАК ЭКСПРЕС, НИКТО БЫ В СВЕТЕ ФОНАРЯ ЧТО-ТО БЛЕСТЯЩЕЕ И ИСХОДИТ ОТТУДА ХРИП, И НЕ ТОПАЛ ПО НОЧАМ

### ISSUE THREAD

**Issue by vasilisaartyomova** [itch2016/dev-union-ua#108]
и как-то раз вечерком, мне пришлось идти в этот овраг почему-то вызывал из памяти роман стругацких «улитка на склоне»…

**Comment by OstapYuriev** [comment]
и не крыс размером с чабычах (хз насколько они огромные) — человек сделал шаг навстречу и пацаны побежали обратно домой в ночь его смерти мне приснилось, будто я со своим сменщиком, который возвращался домой то ли биологом хотя квартирами их назвать трудно дед по 1 сторону, мужик по другую, идут почти молча, обсудили только пропавшего человек
