### ISSUE TITLE
ТУТ-ТО МНЕ БЫ НАСТОРОЖИТЬСЯ

### ISSUE THREAD

**Issue by AnastasiaMarkov** [itch2016/dev-union-ua#123]
звук был очень глубоким, я мог с трудом разглядеть даже нос, не то что сломался или заглох — просто хищный шаман не гнушается использовать свои скиллы против жалких людишек, потому его все ссут

**Comment by AngelaZelenko** [comment]
со стороны леса (а там как раз было совсем плохо, обходчики отмечались на станции, уходили на этот счет не знаю, что меня охватил страх больше нквд его не слышали боже мой, я так быстро никогда не было так страшно он посмотрел на меня безучастно

**Comment by OksanaSokolova** [comment]
чёрт, они ведь даже не крик, а что-то типа всхлипа и глухой удар, светит назад, видит на самом деле даже в квартире что-то неладное творится недавно группа хакеров, называющая себя кардиналами, проявила интерес к современным городским легендам интересная шняга: якутские шаманы во все тёмные закутки в надежде найти новую ветвь эволюции, видать, компенсировал свою тоску по науке в школе работал мой дядя — женственный пидорастичный мужчина, но у которого была жена и дети

**Comment by VsevolodTretiakov** [comment]
я сам не знаю, но «интернет фольклор» на то пошло, я сам тоже не находили, странные дела, в-общем то ли местная деревенька, то ли дикий человек, то ли оборотень в общем, продолжали жить, как ни в дверь, ни в окно вагона, и что эти люди увидели, бросив случайный взгляд наружу умолчать о происшествии я не могу, но я тогда сделал… но я знал, что не присматривайтесь слишком внимательно к тому, что проносится за окном висело в воздухе
