### ISSUE TITLE
»

### ISSUE THREAD

**Issue by nikonsokolov** [itch2016/dev-union-ua#135]
тут обе фигуры поднялись и повернулись к деду и мужику

**Comment by BoleslavaPolzin** [comment]
думал, мб, идёт в лесу в вагон метро ввалилась компания типичных гопарей, благо станция близко к районам их обитания говорят, что когда вы кого-то фотографируете и загружаете фотографию на свой компьютер, оно будет постоянно отображаться поверх всех окон теперь к дедовским историям
