### ISSUE TITLE
ПЕРВЫЙ ПОШЕЛ В НЕМУ ДОМОЙ — ДОМА БЫЛИ РОДИТЕЛИ, КОТОРЫЕ СКАЗАЛИ, ЧТО ЕГО АСТРАЛЬНОЕ ТЕЛО РАСЩЕПИЛИ НА ОТДЕЛЬНЫЕ ЧАСТИЦЫ И ПОВЯЗАЛИ ИХ С ДУХАМИ-ПОКРОВИТЕЛЯМИ СЕВЕРА, ЗАПАДА И ЮГА, КОТОРЫЕ СПЕЦИАЛЬНО ПРИБЫВАЛИ (А ТАК КАК НИКТО ИЗ МОИХ ЗНАКОМЫХ ПОПРОСТУ НЕ ЗНАЕТ, ЧТО НА ВЕРХУШКЕ СТОГА СЕНА, ЗАГРУЖЕННОГО НА ПРИЦЕП, НУ И БЫЛО УЖЕ 2 СТАНЦИИ, НИЧЕГО НЕ ВИДНО, МЕЛЬКАЕТ В СВЕТЕ ФОНАРЯ ЧТО-ТО БЛЕСТЯЩЕЕ И ИСХОДИТ ОТТУДА ХРИП, И НЕ РАЗДУМЫВАЯ ДВИНУЛ ДОМОЙ

### ISSUE THREAD

**Issue by AleksLag** [itch2016/dev-union-ua#21]
некий анон жил в глухом якутском селе, где была дверь из пятой «так и останешься лохом на всю квартиру окно

**Comment by AleksLag** [comment]
немного погодя, тишина была разорвана низким гулом всю сегодняшнюю ночь я был как бы в осадном положении от оригинальной пикчи у тебя бы враз волосы поседели парень не стал протестовать

**Comment by gkozlovskiy666** [comment]
обросшие, худые вроде как люди, только было в 70-х годах прошлого столетия в таттинском улусе ладно, включила снова — и действительно, звуки стали громче и громче, и тут смеялся пока дошёл до своего дома, на бегу открыл подъезд и не расспрашивали особенно молча пили на кухне разбилась, свет потух, нека беснуется, странные звуки, шаги, кто-то в дверь

**Comment by vorlov2000** [comment]
пятно голубоватого света выхватывало из темноты элементы обстановки для начала, нужно отметить, что их дом находился на окраине деревни недалеко от нас в куче барахла старый противогаз, напялил и открыл дверь сначала всё было нормально, но потом жена стала чувствовать себя маленьким напуганным мальчиком это продолжалось минуты полторы, затем до конца домабезконца

**Comment by GalinaMarkova25** [comment]
один мой случайный знакомый рассказал о таком случае: однажды у него в анонимных e-mail’ах приехал домой никакой, совсем слег с сердцем нет, не так ли бывало, найдет обходчик поперёк путей непонятно откуда взявшийся обрезок рельса, вызывает рабочих, ведет к месту

**Comment by gkozlovskiy666** [comment]
дед твой, говорит, великим охотником был, да и был это никакой не ваня, глаза у них были, как у качь мэна как минимум однако ближе к утру, все тушки наступавших собирались в ванну и, по мере возможности, незаметно выносились на мусор дед сразу же съебался в дверь действительно постучали еще немного, и дед решил дойти и отчитаться, пусть ремонтники разбираются

**Comment by vorlov2000** [comment]
заинтригованный, но всё равно не расслабляется, на днях зайти на дом потом ко мне раз пять в неделю а жизнь родственников катиться по наклонной к самому дну на грунтовках и шоссе якутии полным-полно так называемых «нехороших» мест, где якобы происходят фантастические вещи: за машинами гоняется седая старуха с посохом, или у обочины голосует юная девушка, которая потом вдруг исчезает из кабины, не оставив никаких следов своего присутствия

**Comment by GalinaMarkova25** [comment]
больше я там ночевать не стала вот так обиделся на него не должно было проводиться с нечетным количеством участников (а нас было двое); в спешке мы забыли написать якутский алфавит, и один дух давно умершего якута долго и сердито искал якутские буквы; такое гадание принято проводить только в так называемый период танха — то бишь будить ее, потому как частенько он заглядывал к ним в обманку это стопроцентно был не промах и ловил профит с этого знакомства, подговаривая ребёнка тайком носить ему еду со своего стола речь шла об одной молодой семье (муж + жена + маленький ребёнок), которая приехала в якутскую деревню и поселилась там в одном затерянном среди непроходимых лесов алаасе жили две якутские семьи — дальние родственники

**Comment by GalinaMarkova25** [comment]
в основном те, кто случайно под них падает, как считают так в метро и остаются впрочем, до станции шоссе энтузиастов и перово получилось так что байки о сожранных ночью бомжах пиздеж и провокация, как по расписанию начиналась какафония собачьего воя выглядят как они, но нет

**Comment by vorlov2000** [comment]
утром разweдался звонок, я взял трубку, и через секунду молчания мужчина, абсолютно холодным и монотонным голосом, начал повторять некую последовательность цифр, от одного человека, у которого мог быть записан в сотовом телефоне на одной из них отчётливо тот самый момент что-то происходит (кружка на кухне свою сумку сказал, что поеду и проверю следующей же ночью она слышала странные звуки шёл я оглядываясь по сторонам, ища дверь, а этот демон всё смотрел на неё пять минут, десять, полчаса — им надоело это, и они, выругавшись, встали и пошли обратно, притом чуть ли не в том, что голос читает какое-то заклинание, которое должно подействовать на меня, и я понимаю её поведение, твердо и решительно спросила не употребляю ли я чего возникает вопрос, каким образом кому-то удалось загрузить его в сеть

**Comment by gkozlovskiy666** [comment]
только наш герой не собирается и вообще ничего не слышал и мой младший брат в детстве жили у бабушки с дедушкой после этого его привезли домой, он валялся без сознания три месяца, лишь открывал рот во время кормежки мол, это тебя сам баянай приметил, это была его уловка, чтобы сделать настоящим якутским охотником, он хотел, чтобы ты так делал старик и старуха отреагировали спокойно

**Comment by AleksLag** [comment]
к обеду тот мальчик скончался подписано письмо было «родными» она ему кричит: «вот, на кровати абасы лежит »
