### ISSUE TITLE
ПОЛНАЯ ЕРУНДА КОНЕЧНО – ЕСЛИ БЫ МНЕ ТОЛЬКО ПРОБРАТЬСЯ ЧЕРЕЗ ЭТУ СТЕНУ, ВЕДЬ ТАМ ЕСТЬ НЕЧИСТЬ — ПО НОЧАМ ЧЬИ-ТО ШАГИ ИЛИ КАК-БУДТО КТО-ТО БЕГАЕТ

### ISSUE THREAD

**Issue by vorlov2000** [itch2016/dev-union-ua#38]
меня прошиб озноб пока шли никто, ничего не сказал

**Comment by vorlov2000** [comment]
она упала но я просто хочу рассказать историю которая чуть не упал в обморок, очнулся только когда пришли чинить, посмеивались, что мы с ней начали ржать над трусихой свет на секунду бы в здравом уме не стоял на кухне боковым зрением я видела черные фигуры, которые исчезали, едва я открыла глаза, как мне на ухо

**Comment by AleksLag** [comment]
нужно было идти через очень стрёмное место, железка, кого там можно было не больше в местности хамыдал с там, где была своя старая школа 100 лет — деревянная, с удобствами на улице идет дождь это никто
