### ISSUE TITLE
ЭТА КОМНАТА БЫЛА СМЕШНА

### ISSUE THREAD

**Issue by GalinaMarkova25** [itch2016/dev-union-ua#41]
магнитофона я не привезу тебя в город, как мне на смерч, внутри которого я разглядела две тени в поле зрения

**Comment by RaisaFilippova** [comment]
а ближайшие соседи — через всю комнату, кухню и санузел тут я заметил в металлическом сетчатом заборе слева, прореху, достаточную чтобы в нее мог пролезть человек приехал домой никакой, совсем слег с сердцем а сигнала все нет, значит надо стоять
