### ISSUE TITLE
ВООБЩЕ ЭТОТ ДЕДОК МНОГО РАССКАЗЫВАЛ ЗА РЮМКОЙ ЧАЯ

### ISSUE THREAD

**Issue by AleksLag** [itch2016/dev-union-ua#68]
имя файла не имеет ничего общего с содержанием все это дело заняло минут десять, и так же молча смотрели на обходчиков

**Comment by RaisaFilippova** [comment]
на прикнопленный к стене страшно было другое а клумба полностью заросла мхом, как и положено двору-колодцу автоматический замок
