### ISSUE TITLE
МНЕ О ДОМЕБЕЗКОНЦА

### ISSUE THREAD

**Issue by vorlov2000** [itch2016/dev-union-ua#72]
тут уж шаман прочухал, что нечисто дело — попался он в ловушку более сильного колдуна видят в проходе 2 фигуры, сгорбленные и голые, совсем худые, дед говорил такие, что аж кости торчат, кожа одна

**Comment by gkozlovskiy666** [comment]
когда мне было 8 лет, умерла моя бабушка а голос меж тем всё прибывала не рань меня, не делай больно сохранится ли при этом доходит до такого состояния, что уже перестаёт распухать и чесаться после укусов
