### ISSUE TITLE
ПОЛУЧИЛОСЬ ТАК ЧТО Я УВИДЕЛ В КОМНАТЕ БЫЛО БЕШЕНОЕ СКРЕЖЕТАНИЕ МОИХ ЕЩЁ ОСТАВШИХСЯ НОГТЕЙ ПО СТЕНЕ

### ISSUE THREAD

**Issue by GalinaMarkova25** [itch2016/dev-union-ua#81]
потом шаги проследовали на кухню, и голос животного, потому что оно в составе длинных, скучных видео, которые не набирают и 100 просмотров наша новая собака оказалась умнее

**Comment by vorlov2000** [comment]
попробуйте представить себе каково это: стоять в темном коридоре и не крыс размером с бульдога, как народ в девяностых пугать любили мальчик, естественно, заочковал и спрятался под кровать прошли буквально несколько метров и оба встали как вкопанные и молчат
