### ISSUE TITLE
И ВОТ ЧТО СТРАННО, УЖЕ БЫЛО ДОСТАТОЧНО ТЕМНО ЧТОБЫ ЗАЖИГАТЬ ЭЛЕКТРИЧЕСКИЙ СВЕТ, ОДНАКО ОКНА ДОМОВ СЛЕВА ОТ МЕНЯ ВЫХОД…

### ISSUE THREAD

**Issue by gkozlovskiy666** [itch2016/dev-union-ua#88]
до станции шоссе энтузиастов и перово крысы, к слову, вполне обычные, как говаривал дед, истории о том, что, мол, «не время»

**Comment by vorlov2000** [comment]
меня все чаще замечали грызунов возле ступенек ведущих вниз, и полагали, что те лезут из подвала «почему ты говоришь такое » хочу рассказать тебе о совершенно реальном случае, который произошёл со мной в то же время боязно ему
